# Generated by Django 2.0.3 on 2018-03-27 22:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import spending_api.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=15)),
                ('transaction_date', models.DateField()),
                ('path_classification', models.CharField(max_length=200)),
                ('source', models.CharField(max_length=30)),
                ('create_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expression', models.CharField(max_length=200)),
                ('path', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=15)),
                ('amount_mode', models.CharField(max_length=10)),
                ('create_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='WorkFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
                ('public_key', models.CharField(default=spending_api.models.id_generator, max_length=30)),
                ('create_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.CharField(default=spending_api.models.id_generator, max_length=30)),
                ('owner', models.CharField(max_length=30, null=True)),
                ('create_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='workfile',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spending_api.Workspace'),
        ),
        migrations.AddField(
            model_name='rule',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spending_api.Workspace'),
        ),
        migrations.AddField(
            model_name='journal',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spending_api.Workspace'),
        ),
    ]
