# Generated by Django 2.0.3 on 2018-03-28 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spending_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workfile',
            name='original_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
