# Generated by Django 2.0.3 on 2018-04-05 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spending_api', '0004_auto_20180405_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journals', to='spending_api.Workspace'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='spending_api.Workspace'),
        ),
    ]
