# Generated by Django 2.0.3 on 2018-04-09 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spending_api', '0005_auto_20180405_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rule',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='amount_mode',
        ),
        migrations.AddField(
            model_name='rule',
            name='amount_from',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='rule',
            name='amount_to',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='journal',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spending_api.Workspace'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spending_api.Workspace'),
        ),
    ]
