# Generated by Django 2.0.3 on 2018-04-09 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spending_api', '0007_rule_public_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='amount_from',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='rule',
            name='amount_to',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, null=True),
        ),
    ]
