# Generated by Django 2.0.3 on 2018-04-09 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spending_api', '0011_auto_20180409_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='applied_rule',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
